/*
 Navicat Premium Data Transfer

 Source Server         : postgres-local
 Source Server Type    : PostgreSQL
 Source Server Version : 160003 (160003)
 Source Host           : localhost:5432
 Source Catalog        : kafka-explore
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160003 (160003)
 File Encoding         : 65001

 Date: 09/08/2024 09:41:28
*/


-- ----------------------------
-- Sequence structure for product_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "product_id_seq";
CREATE SEQUENCE "product_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for product
-- ----------------------------
DROP TABLE IF EXISTS "product";
CREATE TABLE "product" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "product" varchar(255) COLLATE "pg_catalog"."default",
  "stock" int4,
  "price" numeric(10,2),
  "created_on" timestamp(6),
  "row_number" int4
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "product_id_seq"
OWNED BY "product"."id";
SELECT setval('"product_id_seq"', 86445, true);

-- ----------------------------
-- Primary Key structure for table product
-- ----------------------------
ALTER TABLE "product" ADD CONSTRAINT "product_pkey" PRIMARY KEY ("id");
